version: "3"
services:
  extraction:
    build:
      context: extraction/
      dockerfile: Containerfile
    image: extraction
    ports:
      - 8888:8888
    volumes:
      - ./extraction/:/extraction/:Z
      - ./outputs/:/outputs/:Z
    command: [
      "bash",
      "-c",
      "jupyter lab --no-browser --ip=0.0.0.0 --port 8888 --allow-root --notebook-dir=/extraction",
    ]
  summarization:
    build:
      context: summarization/
      dockerfile: Containerfile
    image: text-summarization
    ports:
      - 8889:8889
    volumes:
      - ./summarization:/summarization:Z
      - ./outputs:/outputs/:Z
    env_file:
      - ./ENV
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    security_opt:
      - "label=disable"
