version: "3"
services:
  extraction:
    build:
      context: extraction/
      dockerfile: Containerfile
    image: extraction
    ports:
      - 8888:8888
    volumes:
      - ./extraction/:/extraction/:Z
      - ./outputs/:/outputs/:Z
    command: [
      "bash",
      "-c",
      "jupyter lab --no-browser --ip=0.0.0.0 --port 8888 --allow-root --notebook-dir=/extraction",
    ]
