FROM python:3.11-slim-bookworm

RUN apt-get update && apt-get install -y \
    git \
    python3-pip \
    ffmpeg \
    libsm6 \
    libxext6

COPY requirements.txt /requirements.txt

RUN pip install -r requirements.txt
